# Generated by Django 4.1.4 on 2023-01-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "LittleLemonDRF",
            "0002_cart_category_menuitem_ordemitem_order_delete_rating_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="featured",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
