# Generated by Django 4.1.4 on 2023-01-11 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("LittleLemonDRF", "0003_alter_menuitem_featured"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrdemItem",
            new_name="OrderItem",
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="LittleLemonDRF.order"
            ),
        ),
    ]
