# Generated by Django 4.1.4 on 2023-01-11 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LittleLemonDRF", "0004_rename_ordemitem_orderitem_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                db_index=True,
                default=datetime.datetime(
                    2023, 1, 11, 23, 29, 12, 748586, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
